source "https://rubygems.org"

gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "rake"

gem "require_all"
gem "sqlite3"
gem "pry"

gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
